### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by ilikealotgithub1234**
@rickyc this is the pull rquest

### CODE REVIEW

**Comment by rickyc** [comment]
Close! It should be the other way around. Right now you are trying to merge your `master` code into `homework-0`. The idea is that once your homework is complete and checked, it will get merged into master. Does that make sense?

**Comment by ilikealotgithub1234** [comment]
oh i just resubmitted it
Please let me know if it is correct thanks

**Comment by rickyc** [comment]
Well, what's happening right now is `master` has 3 commits and `homework-0` has 2. That means `master` branch is ahead or has more work on it done than `homework-0`. You need homework-0 to have more commits than master for this to work. Close this PR and open a new one when that's done.

**Comment by ilikealotgithub1234** [comment]
@rickyc what is a RC?

**Comment by rickyc** [comment]
PR? That would be a Pull Request.

**Comment by ilikealotgithub1234** [comment]
@rickyc how would i create a new pull request for the same repo?

**Comment by rickyc** [comment]
Go to the website and click on the green button to merge your pull request
for now. Make sure you click on the arrow and change it to squash and merge
pull request. When that happens, you should see that branch homework-0 and
master are identical. Then go to your desktop, checkout homework-0 and make
a change to the file. Save and commit it then open a new PR.

**Comment by rickyc** [comment]
I forgot to mention you can also open / close PRs on the website.

**Comment by rickyc** [comment]
I would say you've basically mastered PR and gone over everything I wanted
you to. Responding to commit messages, making multiple commits, merging
branches. So you're basically done :). The only thing in the future is to
make sure you merge the right branches.

**Pull request merged**
